version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: amacame_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
    volumes:
       # - /home/helldev/workspace/docker_apps/amacame_db:/var/lib/postgresql/data // linux
      - db:/var/lib/postgresql/data
volumes:
  db: