create table authentication.authentication_token (is_active boolean not null, creation_date timestamp(6), expiration_date timestamp(6), id bigserial not null, token TEXT, username varchar(255), primary key (id));
create table authentication.permissions (id bigserial not null, name varchar(255) not null unique, primary key (id));
create table authentication.roles (id bigserial not null, role_enum varchar(255) check (role_enum in ('USER','ADMIN')), primary key (id));
create table authentication.users (user_id bigserial not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (user_id));
create table billing.bill (bill_date date, bill_detail_total numeric(38,2), bill_profit numeric(38,2), bill_total numeric(38,2), has_bill_promo boolean not null, has_product_promo boolean not null, is_active boolean not null, bill_detail_bill_detail_id bigint unique, bill_id bigserial not null, created_at timestamp(6) with time zone, promo_promo_id bigint, updated_at timestamp(6) with time zone, bill_description varchar(255), bill_status varchar(255) check (bill_status in ('PAGADO','PENDIENTE','DEVUELTO','CANCELADO')), primary key (bill_id));
create table billing.bill_detail (bill_detail_id bigserial not null, created_at timestamp(6) with time zone, updated_at timestamp(6) with time zone, primary key (bill_detail_id));
create table billing.bill_detail_line (has_promo boolean not null, total_price_by_product numeric(38,2), total_profit_by_product numeric(38,2), bill_detail_line_id bigserial not null, product_id bigint, promo_id bigint, quantity bigint, primary key (bill_detail_line_id));
create table product.brand (is_active boolean not null, brand_id bigserial not null, created_at timestamp(6) with time zone, updated_at timestamp(6) with time zone, brand_name varchar(255), primary key (brand_id));
create table product.product (is_active boolean not null, product_profit numeric(38,2), product_purchase_price numeric(38,2), product_sale_price numeric(38,2), product_stock integer, brand_id bigint, created_at timestamp(6) with time zone, product_id bigserial not null, updated_at timestamp(6) with time zone, product_name varchar(255), primary key (product_id));
create table promotion.promos (is_active boolean not null, promo_value numeric(38,2), created_at timestamp(6) with time zone, promo_id bigserial not null, special_promox bigint, special_promoy bigint, updated_at timestamp(6) with time zone, promo_description varchar(255), promo_name varchar(255), promo_scope varchar(255) check (promo_scope in ('BILL','PRODUCT')), promo_type varchar(255) check (promo_type in ('DISCOUNTPRODUCT','DISCOUNTBILL','SPECIALPROMOS')), primary key (promo_id));
create table bill_detail_bill_detail_lines (bill_detail_bill_detail_id bigint not null, bill_detail_lines_bill_detail_line_id bigint not null unique);
create table role_permissions (permission_id bigint not null, role_id bigint not null);
create table user_roles (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id));
alter table if exists billing.bill add constraint FKbgc7fd3apns4c8eve4mldngfy foreign key (bill_detail_bill_detail_id) references billing.bill_detail;
alter table if exists billing.bill add constraint FKjku16wroyeo5dwtttuc1oqayl foreign key (promo_promo_id) references promotion.promos;
alter table if exists billing.bill_detail_line add constraint FKhw996cq77xw0j7gtb6a76u67v foreign key (product_id) references product.product;
alter table if exists billing.bill_detail_line add constraint FKd2jxpimpjv1jnak1ykitf7q4n foreign key (promo_id) references promotion.promos;
alter table if exists product.product add constraint FKs6cydsualtsrprvlf2bb3lcam foreign key (brand_id) references product.brand;
alter table if exists bill_detail_bill_detail_lines add constraint FK7rhphr4hm72h3wpfurnqugm9i foreign key (bill_detail_lines_bill_detail_line_id) references billing.bill_detail_line;
alter table if exists bill_detail_bill_detail_lines add constraint FK6st8twclr6j0k050mujxxb44k foreign key (bill_detail_bill_detail_id) references billing.bill_detail;
alter table if exists role_permissions add constraint FKegdk29eiy7mdtefy5c7eirr6e foreign key (permission_id) references authentication.permissions;
alter table if exists role_permissions add constraint FKn5fotdgk8d1xvo8nav9uv3muc foreign key (role_id) references authentication.roles;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references authentication.roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references authentication.users;
